name: Pull/Run Unit tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test E2E'
    steps:
      - uses: actions/checkout@v4
        with:
          repository: modbus2mqtt/modbus2mqtt.dev
          path: .
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Wait for other workflow run or continue
        id: init
        run: |
          gh auth status
          owner=""
          if [ "${{github.event.act.owner}}" != '' ]
          then
            owner="-o ${{github.event.act.owner}}"
          else
            owner="-o ${{github.repository_owner}}"
          fi
          echo "owner=$owner" >> "$GITHUB_OUTPUT"
          bin/pulls.py $owner testorwait --noexec ${{github.event.pull_request.base.repo.name}}:${{github.event.number}} "${{github.event.pull_request.body}}"  >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute all tests
        id: execute
        if: steps.init.outputs.type== 'testrunner'
        run: | 
          bin/pulls.py   ${{steps.init.outputs.owner}} init -b main 
          echo "::group::syncpull"
          bin/pulls.py  ${{steps.init.outputs.owner}} syncpull --pullrequest ${{github.event.pull_request.base.repo.name}}:${{github.event.number}} --pulltext "${{github.event.pull_request.body}}" pull${{github.event.pull_request.number}}
          echo "::endgroup::"
          echo "::group::dependencies local"
          bin/pulls.py  ${{steps.init.outputs.owner}} dependencies local
          echo "::endgroup::"
          echo "::group::build"
          bin/pulls.py  ${{steps.init.outputs.owner}} build
          echo "::endgroup::"
          echo "::group::testorwait"
          bin/pulls.py ${{steps.init.outputs.owner}} testorwait ${{github.event.pull_request.base.repo.name}}:${{github.event.number}} "${{github.event.pull_request.body}}"  >> "$GITHUB_OUTPUT"
          echo "::endgroup::"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}



       
      
