on:
  push:
    tags:
      - "v*"
jobs:
  release:
    uses: modbus2mqtt/specification.shared/.github/workflows/release.yml@main
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

  
